# Get Product 
GET  http://localhost:8800/api/v1/products

###
# Create Product
POST http://localhost:8800/api/v1/product/new
Content-Type: application/json

{
    "name":"array-test",
    "price":"9999",
    "description":"imageid",
    "category":"test",
    "images":{
        "publicId":"id",
        "url":"idturl2"
    }
}

###
# Update Product
PUT http://localhost:8800/api/v1/product/62a8c7745d031cb55b714087
Content-Type: application/json

{
    "name":"5-product-test",
    "price":"5555",
    "description":"test product",
    "category":"test",
    "images":{
        "publicId":"Id",
        "url":"url"
    }
}


###
# Delete Product
DELETE  http://localhost:8800/api/v1/product/62a4ef872f72e0358a3092cc


###
#Product Detials  
GET  http://localhost:8800/api/v1/product/62a4efa91862095d49959208


###
